/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as TestingImport } from './routes/testing'
import { Route as TentangKamiImport } from './routes/tentangKami'
import { Route as RiwayatImport } from './routes/riwayat'
import { Route as RegisterImport } from './routes/register'
import { Route as PrestasiImport } from './routes/prestasi'
import { Route as PengajuanImport } from './routes/pengajuan'
import { Route as InformasiImport } from './routes/informasi'
import { Route as ForgetpassImport } from './routes/forgetpass'
import { Route as DokumenImport } from './routes/dokumen'
import { Route as RuanganIndexImport } from './routes/ruangan/index'
import { Route as AdminIndexImport } from './routes/admin/index'
import { Route as AdminPeminjamanIndexImport } from './routes/admin/peminjaman/index'
import { Route as AdminPeminjamanCreateImport } from './routes/admin/peminjaman/create'

// Create Virtual Routes

const LoginLazyImport = createFileRoute('/login')()
const IndexLazyImport = createFileRoute('/')()
const RuanganIdLazyImport = createFileRoute('/ruangan/$id')()
const AdminTagIndexLazyImport = createFileRoute('/admin/tag/')()
const AdminStudentIndexLazyImport = createFileRoute('/admin/student/')()
const AdminRuanganIndexLazyImport = createFileRoute('/admin/ruangan/')()
const AdminFasilitasIndexLazyImport = createFileRoute('/admin/fasilitas/')()
const AdminBerkasIndexLazyImport = createFileRoute('/admin/berkas/')()
const AdminAchievementIndexLazyImport = createFileRoute('/admin/achievement/')()
const AdminTagCreateLazyImport = createFileRoute('/admin/tag/create')()
const AdminStudentCreateLazyImport = createFileRoute('/admin/student/create')()
const AdminRuanganCreateLazyImport = createFileRoute('/admin/ruangan/create')()
const AdminFasilitasCreateLazyImport = createFileRoute(
  '/admin/fasilitas/create',
)()
const AdminBerkasCreateLazyImport = createFileRoute('/admin/berkas/create')()
const AdminAchievementCreateLazyImport = createFileRoute(
  '/admin/achievement/create',
)()
const AdminAchievementIdLazyImport = createFileRoute('/admin/achievement/$id')()
const AdminTagEditIdLazyImport = createFileRoute('/admin/tag/edit/$id')()
const AdminStudentEditIdLazyImport = createFileRoute(
  '/admin/student/edit/$id',
)()
const AdminRuanganEditIdLazyImport = createFileRoute(
  '/admin/ruangan/edit/$id',
)()
const AdminPeminjamanEditIdLazyImport = createFileRoute(
  '/admin/peminjaman/edit/$id',
)()
const AdminPeminjamanDetailIdLazyImport = createFileRoute(
  '/admin/peminjaman/detail/$id',
)()
const AdminFasilitasEditIdLazyImport = createFileRoute(
  '/admin/fasilitas/edit/$id',
)()
const AdminBerkasEditIdLazyImport = createFileRoute('/admin/berkas/edit/$id')()
const AdminAchievementEditIdLazyImport = createFileRoute(
  '/admin/achievement/edit/$id',
)()

// Create/Update Routes

const LoginLazyRoute = LoginLazyImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/login.lazy').then((d) => d.Route))

const TestingRoute = TestingImport.update({
  id: '/testing',
  path: '/testing',
  getParentRoute: () => rootRoute,
} as any)

const TentangKamiRoute = TentangKamiImport.update({
  id: '/tentangKami',
  path: '/tentangKami',
  getParentRoute: () => rootRoute,
} as any)

const RiwayatRoute = RiwayatImport.update({
  id: '/riwayat',
  path: '/riwayat',
  getParentRoute: () => rootRoute,
} as any)

const RegisterRoute = RegisterImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRoute,
} as any)

const PrestasiRoute = PrestasiImport.update({
  id: '/prestasi',
  path: '/prestasi',
  getParentRoute: () => rootRoute,
} as any)

const PengajuanRoute = PengajuanImport.update({
  id: '/pengajuan',
  path: '/pengajuan',
  getParentRoute: () => rootRoute,
} as any)

const InformasiRoute = InformasiImport.update({
  id: '/informasi',
  path: '/informasi',
  getParentRoute: () => rootRoute,
} as any)

const ForgetpassRoute = ForgetpassImport.update({
  id: '/forgetpass',
  path: '/forgetpass',
  getParentRoute: () => rootRoute,
} as any)

const DokumenRoute = DokumenImport.update({
  id: '/dokumen',
  path: '/dokumen',
  getParentRoute: () => rootRoute,
} as any)

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const RuanganIndexRoute = RuanganIndexImport.update({
  id: '/ruangan/',
  path: '/ruangan/',
  getParentRoute: () => rootRoute,
} as any)

const AdminIndexRoute = AdminIndexImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRoute,
} as any)

const RuanganIdLazyRoute = RuanganIdLazyImport.update({
  id: '/ruangan/$id',
  path: '/ruangan/$id',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/ruangan/$id.lazy').then((d) => d.Route))

const AdminTagIndexLazyRoute = AdminTagIndexLazyImport.update({
  id: '/admin/tag/',
  path: '/admin/tag/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/admin/tag/index.lazy').then((d) => d.Route),
)

const AdminStudentIndexLazyRoute = AdminStudentIndexLazyImport.update({
  id: '/admin/student/',
  path: '/admin/student/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/admin/student/index.lazy').then((d) => d.Route),
)

const AdminRuanganIndexLazyRoute = AdminRuanganIndexLazyImport.update({
  id: '/admin/ruangan/',
  path: '/admin/ruangan/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/admin/ruangan/index.lazy').then((d) => d.Route),
)

const AdminFasilitasIndexLazyRoute = AdminFasilitasIndexLazyImport.update({
  id: '/admin/fasilitas/',
  path: '/admin/fasilitas/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/admin/fasilitas/index.lazy').then((d) => d.Route),
)

const AdminBerkasIndexLazyRoute = AdminBerkasIndexLazyImport.update({
  id: '/admin/berkas/',
  path: '/admin/berkas/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/admin/berkas/index.lazy').then((d) => d.Route),
)

const AdminAchievementIndexLazyRoute = AdminAchievementIndexLazyImport.update({
  id: '/admin/achievement/',
  path: '/admin/achievement/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/admin/achievement/index.lazy').then((d) => d.Route),
)

const AdminPeminjamanIndexRoute = AdminPeminjamanIndexImport.update({
  id: '/admin/peminjaman/',
  path: '/admin/peminjaman/',
  getParentRoute: () => rootRoute,
} as any)

const AdminTagCreateLazyRoute = AdminTagCreateLazyImport.update({
  id: '/admin/tag/create',
  path: '/admin/tag/create',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/admin/tag/create.lazy').then((d) => d.Route),
)

const AdminStudentCreateLazyRoute = AdminStudentCreateLazyImport.update({
  id: '/admin/student/create',
  path: '/admin/student/create',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/admin/student/create.lazy').then((d) => d.Route),
)

const AdminRuanganCreateLazyRoute = AdminRuanganCreateLazyImport.update({
  id: '/admin/ruangan/create',
  path: '/admin/ruangan/create',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/admin/ruangan/create.lazy').then((d) => d.Route),
)

const AdminFasilitasCreateLazyRoute = AdminFasilitasCreateLazyImport.update({
  id: '/admin/fasilitas/create',
  path: '/admin/fasilitas/create',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/admin/fasilitas/create.lazy').then((d) => d.Route),
)

const AdminBerkasCreateLazyRoute = AdminBerkasCreateLazyImport.update({
  id: '/admin/berkas/create',
  path: '/admin/berkas/create',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/admin/berkas/create.lazy').then((d) => d.Route),
)

const AdminAchievementCreateLazyRoute = AdminAchievementCreateLazyImport.update(
  {
    id: '/admin/achievement/create',
    path: '/admin/achievement/create',
    getParentRoute: () => rootRoute,
  } as any,
).lazy(() =>
  import('./routes/admin/achievement/create.lazy').then((d) => d.Route),
)

const AdminAchievementIdLazyRoute = AdminAchievementIdLazyImport.update({
  id: '/admin/achievement/$id',
  path: '/admin/achievement/$id',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/admin/achievement/$id.lazy').then((d) => d.Route),
)

const AdminPeminjamanCreateRoute = AdminPeminjamanCreateImport.update({
  id: '/admin/peminjaman/create',
  path: '/admin/peminjaman/create',
  getParentRoute: () => rootRoute,
} as any)

const AdminTagEditIdLazyRoute = AdminTagEditIdLazyImport.update({
  id: '/admin/tag/edit/$id',
  path: '/admin/tag/edit/$id',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/admin/tag/edit/$id.lazy').then((d) => d.Route),
)

const AdminStudentEditIdLazyRoute = AdminStudentEditIdLazyImport.update({
  id: '/admin/student/edit/$id',
  path: '/admin/student/edit/$id',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/admin/student/edit/$id.lazy').then((d) => d.Route),
)

const AdminRuanganEditIdLazyRoute = AdminRuanganEditIdLazyImport.update({
  id: '/admin/ruangan/edit/$id',
  path: '/admin/ruangan/edit/$id',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/admin/ruangan/edit/$id.lazy').then((d) => d.Route),
)

const AdminPeminjamanEditIdLazyRoute = AdminPeminjamanEditIdLazyImport.update({
  id: '/admin/peminjaman/edit/$id',
  path: '/admin/peminjaman/edit/$id',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/admin/peminjaman/edit/$id.lazy').then((d) => d.Route),
)

const AdminPeminjamanDetailIdLazyRoute =
  AdminPeminjamanDetailIdLazyImport.update({
    id: '/admin/peminjaman/detail/$id',
    path: '/admin/peminjaman/detail/$id',
    getParentRoute: () => rootRoute,
  } as any).lazy(() =>
    import('./routes/admin/peminjaman/detail/$id.lazy').then((d) => d.Route),
  )

const AdminFasilitasEditIdLazyRoute = AdminFasilitasEditIdLazyImport.update({
  id: '/admin/fasilitas/edit/$id',
  path: '/admin/fasilitas/edit/$id',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/admin/fasilitas/edit/$id.lazy').then((d) => d.Route),
)

const AdminBerkasEditIdLazyRoute = AdminBerkasEditIdLazyImport.update({
  id: '/admin/berkas/edit/$id',
  path: '/admin/berkas/edit/$id',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/admin/berkas/edit/$id.lazy').then((d) => d.Route),
)

const AdminAchievementEditIdLazyRoute = AdminAchievementEditIdLazyImport.update(
  {
    id: '/admin/achievement/edit/$id',
    path: '/admin/achievement/edit/$id',
    getParentRoute: () => rootRoute,
  } as any,
).lazy(() =>
  import('./routes/admin/achievement/edit/$id.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/dokumen': {
      id: '/dokumen'
      path: '/dokumen'
      fullPath: '/dokumen'
      preLoaderRoute: typeof DokumenImport
      parentRoute: typeof rootRoute
    }
    '/forgetpass': {
      id: '/forgetpass'
      path: '/forgetpass'
      fullPath: '/forgetpass'
      preLoaderRoute: typeof ForgetpassImport
      parentRoute: typeof rootRoute
    }
    '/informasi': {
      id: '/informasi'
      path: '/informasi'
      fullPath: '/informasi'
      preLoaderRoute: typeof InformasiImport
      parentRoute: typeof rootRoute
    }
    '/pengajuan': {
      id: '/pengajuan'
      path: '/pengajuan'
      fullPath: '/pengajuan'
      preLoaderRoute: typeof PengajuanImport
      parentRoute: typeof rootRoute
    }
    '/prestasi': {
      id: '/prestasi'
      path: '/prestasi'
      fullPath: '/prestasi'
      preLoaderRoute: typeof PrestasiImport
      parentRoute: typeof rootRoute
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterImport
      parentRoute: typeof rootRoute
    }
    '/riwayat': {
      id: '/riwayat'
      path: '/riwayat'
      fullPath: '/riwayat'
      preLoaderRoute: typeof RiwayatImport
      parentRoute: typeof rootRoute
    }
    '/tentangKami': {
      id: '/tentangKami'
      path: '/tentangKami'
      fullPath: '/tentangKami'
      preLoaderRoute: typeof TentangKamiImport
      parentRoute: typeof rootRoute
    }
    '/testing': {
      id: '/testing'
      path: '/testing'
      fullPath: '/testing'
      preLoaderRoute: typeof TestingImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginLazyImport
      parentRoute: typeof rootRoute
    }
    '/ruangan/$id': {
      id: '/ruangan/$id'
      path: '/ruangan/$id'
      fullPath: '/ruangan/$id'
      preLoaderRoute: typeof RuanganIdLazyImport
      parentRoute: typeof rootRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminIndexImport
      parentRoute: typeof rootRoute
    }
    '/ruangan/': {
      id: '/ruangan/'
      path: '/ruangan'
      fullPath: '/ruangan'
      preLoaderRoute: typeof RuanganIndexImport
      parentRoute: typeof rootRoute
    }
    '/admin/peminjaman/create': {
      id: '/admin/peminjaman/create'
      path: '/admin/peminjaman/create'
      fullPath: '/admin/peminjaman/create'
      preLoaderRoute: typeof AdminPeminjamanCreateImport
      parentRoute: typeof rootRoute
    }
    '/admin/achievement/$id': {
      id: '/admin/achievement/$id'
      path: '/admin/achievement/$id'
      fullPath: '/admin/achievement/$id'
      preLoaderRoute: typeof AdminAchievementIdLazyImport
      parentRoute: typeof rootRoute
    }
    '/admin/achievement/create': {
      id: '/admin/achievement/create'
      path: '/admin/achievement/create'
      fullPath: '/admin/achievement/create'
      preLoaderRoute: typeof AdminAchievementCreateLazyImport
      parentRoute: typeof rootRoute
    }
    '/admin/berkas/create': {
      id: '/admin/berkas/create'
      path: '/admin/berkas/create'
      fullPath: '/admin/berkas/create'
      preLoaderRoute: typeof AdminBerkasCreateLazyImport
      parentRoute: typeof rootRoute
    }
    '/admin/fasilitas/create': {
      id: '/admin/fasilitas/create'
      path: '/admin/fasilitas/create'
      fullPath: '/admin/fasilitas/create'
      preLoaderRoute: typeof AdminFasilitasCreateLazyImport
      parentRoute: typeof rootRoute
    }
    '/admin/ruangan/create': {
      id: '/admin/ruangan/create'
      path: '/admin/ruangan/create'
      fullPath: '/admin/ruangan/create'
      preLoaderRoute: typeof AdminRuanganCreateLazyImport
      parentRoute: typeof rootRoute
    }
    '/admin/student/create': {
      id: '/admin/student/create'
      path: '/admin/student/create'
      fullPath: '/admin/student/create'
      preLoaderRoute: typeof AdminStudentCreateLazyImport
      parentRoute: typeof rootRoute
    }
    '/admin/tag/create': {
      id: '/admin/tag/create'
      path: '/admin/tag/create'
      fullPath: '/admin/tag/create'
      preLoaderRoute: typeof AdminTagCreateLazyImport
      parentRoute: typeof rootRoute
    }
    '/admin/peminjaman/': {
      id: '/admin/peminjaman/'
      path: '/admin/peminjaman'
      fullPath: '/admin/peminjaman'
      preLoaderRoute: typeof AdminPeminjamanIndexImport
      parentRoute: typeof rootRoute
    }
    '/admin/achievement/': {
      id: '/admin/achievement/'
      path: '/admin/achievement'
      fullPath: '/admin/achievement'
      preLoaderRoute: typeof AdminAchievementIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/admin/berkas/': {
      id: '/admin/berkas/'
      path: '/admin/berkas'
      fullPath: '/admin/berkas'
      preLoaderRoute: typeof AdminBerkasIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/admin/fasilitas/': {
      id: '/admin/fasilitas/'
      path: '/admin/fasilitas'
      fullPath: '/admin/fasilitas'
      preLoaderRoute: typeof AdminFasilitasIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/admin/ruangan/': {
      id: '/admin/ruangan/'
      path: '/admin/ruangan'
      fullPath: '/admin/ruangan'
      preLoaderRoute: typeof AdminRuanganIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/admin/student/': {
      id: '/admin/student/'
      path: '/admin/student'
      fullPath: '/admin/student'
      preLoaderRoute: typeof AdminStudentIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/admin/tag/': {
      id: '/admin/tag/'
      path: '/admin/tag'
      fullPath: '/admin/tag'
      preLoaderRoute: typeof AdminTagIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/admin/achievement/edit/$id': {
      id: '/admin/achievement/edit/$id'
      path: '/admin/achievement/edit/$id'
      fullPath: '/admin/achievement/edit/$id'
      preLoaderRoute: typeof AdminAchievementEditIdLazyImport
      parentRoute: typeof rootRoute
    }
    '/admin/berkas/edit/$id': {
      id: '/admin/berkas/edit/$id'
      path: '/admin/berkas/edit/$id'
      fullPath: '/admin/berkas/edit/$id'
      preLoaderRoute: typeof AdminBerkasEditIdLazyImport
      parentRoute: typeof rootRoute
    }
    '/admin/fasilitas/edit/$id': {
      id: '/admin/fasilitas/edit/$id'
      path: '/admin/fasilitas/edit/$id'
      fullPath: '/admin/fasilitas/edit/$id'
      preLoaderRoute: typeof AdminFasilitasEditIdLazyImport
      parentRoute: typeof rootRoute
    }
    '/admin/peminjaman/detail/$id': {
      id: '/admin/peminjaman/detail/$id'
      path: '/admin/peminjaman/detail/$id'
      fullPath: '/admin/peminjaman/detail/$id'
      preLoaderRoute: typeof AdminPeminjamanDetailIdLazyImport
      parentRoute: typeof rootRoute
    }
    '/admin/peminjaman/edit/$id': {
      id: '/admin/peminjaman/edit/$id'
      path: '/admin/peminjaman/edit/$id'
      fullPath: '/admin/peminjaman/edit/$id'
      preLoaderRoute: typeof AdminPeminjamanEditIdLazyImport
      parentRoute: typeof rootRoute
    }
    '/admin/ruangan/edit/$id': {
      id: '/admin/ruangan/edit/$id'
      path: '/admin/ruangan/edit/$id'
      fullPath: '/admin/ruangan/edit/$id'
      preLoaderRoute: typeof AdminRuanganEditIdLazyImport
      parentRoute: typeof rootRoute
    }
    '/admin/student/edit/$id': {
      id: '/admin/student/edit/$id'
      path: '/admin/student/edit/$id'
      fullPath: '/admin/student/edit/$id'
      preLoaderRoute: typeof AdminStudentEditIdLazyImport
      parentRoute: typeof rootRoute
    }
    '/admin/tag/edit/$id': {
      id: '/admin/tag/edit/$id'
      path: '/admin/tag/edit/$id'
      fullPath: '/admin/tag/edit/$id'
      preLoaderRoute: typeof AdminTagEditIdLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/dokumen': typeof DokumenRoute
  '/forgetpass': typeof ForgetpassRoute
  '/informasi': typeof InformasiRoute
  '/pengajuan': typeof PengajuanRoute
  '/prestasi': typeof PrestasiRoute
  '/register': typeof RegisterRoute
  '/riwayat': typeof RiwayatRoute
  '/tentangKami': typeof TentangKamiRoute
  '/testing': typeof TestingRoute
  '/login': typeof LoginLazyRoute
  '/ruangan/$id': typeof RuanganIdLazyRoute
  '/admin': typeof AdminIndexRoute
  '/ruangan': typeof RuanganIndexRoute
  '/admin/peminjaman/create': typeof AdminPeminjamanCreateRoute
  '/admin/achievement/$id': typeof AdminAchievementIdLazyRoute
  '/admin/achievement/create': typeof AdminAchievementCreateLazyRoute
  '/admin/berkas/create': typeof AdminBerkasCreateLazyRoute
  '/admin/fasilitas/create': typeof AdminFasilitasCreateLazyRoute
  '/admin/ruangan/create': typeof AdminRuanganCreateLazyRoute
  '/admin/student/create': typeof AdminStudentCreateLazyRoute
  '/admin/tag/create': typeof AdminTagCreateLazyRoute
  '/admin/peminjaman': typeof AdminPeminjamanIndexRoute
  '/admin/achievement': typeof AdminAchievementIndexLazyRoute
  '/admin/berkas': typeof AdminBerkasIndexLazyRoute
  '/admin/fasilitas': typeof AdminFasilitasIndexLazyRoute
  '/admin/ruangan': typeof AdminRuanganIndexLazyRoute
  '/admin/student': typeof AdminStudentIndexLazyRoute
  '/admin/tag': typeof AdminTagIndexLazyRoute
  '/admin/achievement/edit/$id': typeof AdminAchievementEditIdLazyRoute
  '/admin/berkas/edit/$id': typeof AdminBerkasEditIdLazyRoute
  '/admin/fasilitas/edit/$id': typeof AdminFasilitasEditIdLazyRoute
  '/admin/peminjaman/detail/$id': typeof AdminPeminjamanDetailIdLazyRoute
  '/admin/peminjaman/edit/$id': typeof AdminPeminjamanEditIdLazyRoute
  '/admin/ruangan/edit/$id': typeof AdminRuanganEditIdLazyRoute
  '/admin/student/edit/$id': typeof AdminStudentEditIdLazyRoute
  '/admin/tag/edit/$id': typeof AdminTagEditIdLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/dokumen': typeof DokumenRoute
  '/forgetpass': typeof ForgetpassRoute
  '/informasi': typeof InformasiRoute
  '/pengajuan': typeof PengajuanRoute
  '/prestasi': typeof PrestasiRoute
  '/register': typeof RegisterRoute
  '/riwayat': typeof RiwayatRoute
  '/tentangKami': typeof TentangKamiRoute
  '/testing': typeof TestingRoute
  '/login': typeof LoginLazyRoute
  '/ruangan/$id': typeof RuanganIdLazyRoute
  '/admin': typeof AdminIndexRoute
  '/ruangan': typeof RuanganIndexRoute
  '/admin/peminjaman/create': typeof AdminPeminjamanCreateRoute
  '/admin/achievement/$id': typeof AdminAchievementIdLazyRoute
  '/admin/achievement/create': typeof AdminAchievementCreateLazyRoute
  '/admin/berkas/create': typeof AdminBerkasCreateLazyRoute
  '/admin/fasilitas/create': typeof AdminFasilitasCreateLazyRoute
  '/admin/ruangan/create': typeof AdminRuanganCreateLazyRoute
  '/admin/student/create': typeof AdminStudentCreateLazyRoute
  '/admin/tag/create': typeof AdminTagCreateLazyRoute
  '/admin/peminjaman': typeof AdminPeminjamanIndexRoute
  '/admin/achievement': typeof AdminAchievementIndexLazyRoute
  '/admin/berkas': typeof AdminBerkasIndexLazyRoute
  '/admin/fasilitas': typeof AdminFasilitasIndexLazyRoute
  '/admin/ruangan': typeof AdminRuanganIndexLazyRoute
  '/admin/student': typeof AdminStudentIndexLazyRoute
  '/admin/tag': typeof AdminTagIndexLazyRoute
  '/admin/achievement/edit/$id': typeof AdminAchievementEditIdLazyRoute
  '/admin/berkas/edit/$id': typeof AdminBerkasEditIdLazyRoute
  '/admin/fasilitas/edit/$id': typeof AdminFasilitasEditIdLazyRoute
  '/admin/peminjaman/detail/$id': typeof AdminPeminjamanDetailIdLazyRoute
  '/admin/peminjaman/edit/$id': typeof AdminPeminjamanEditIdLazyRoute
  '/admin/ruangan/edit/$id': typeof AdminRuanganEditIdLazyRoute
  '/admin/student/edit/$id': typeof AdminStudentEditIdLazyRoute
  '/admin/tag/edit/$id': typeof AdminTagEditIdLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/dokumen': typeof DokumenRoute
  '/forgetpass': typeof ForgetpassRoute
  '/informasi': typeof InformasiRoute
  '/pengajuan': typeof PengajuanRoute
  '/prestasi': typeof PrestasiRoute
  '/register': typeof RegisterRoute
  '/riwayat': typeof RiwayatRoute
  '/tentangKami': typeof TentangKamiRoute
  '/testing': typeof TestingRoute
  '/login': typeof LoginLazyRoute
  '/ruangan/$id': typeof RuanganIdLazyRoute
  '/admin/': typeof AdminIndexRoute
  '/ruangan/': typeof RuanganIndexRoute
  '/admin/peminjaman/create': typeof AdminPeminjamanCreateRoute
  '/admin/achievement/$id': typeof AdminAchievementIdLazyRoute
  '/admin/achievement/create': typeof AdminAchievementCreateLazyRoute
  '/admin/berkas/create': typeof AdminBerkasCreateLazyRoute
  '/admin/fasilitas/create': typeof AdminFasilitasCreateLazyRoute
  '/admin/ruangan/create': typeof AdminRuanganCreateLazyRoute
  '/admin/student/create': typeof AdminStudentCreateLazyRoute
  '/admin/tag/create': typeof AdminTagCreateLazyRoute
  '/admin/peminjaman/': typeof AdminPeminjamanIndexRoute
  '/admin/achievement/': typeof AdminAchievementIndexLazyRoute
  '/admin/berkas/': typeof AdminBerkasIndexLazyRoute
  '/admin/fasilitas/': typeof AdminFasilitasIndexLazyRoute
  '/admin/ruangan/': typeof AdminRuanganIndexLazyRoute
  '/admin/student/': typeof AdminStudentIndexLazyRoute
  '/admin/tag/': typeof AdminTagIndexLazyRoute
  '/admin/achievement/edit/$id': typeof AdminAchievementEditIdLazyRoute
  '/admin/berkas/edit/$id': typeof AdminBerkasEditIdLazyRoute
  '/admin/fasilitas/edit/$id': typeof AdminFasilitasEditIdLazyRoute
  '/admin/peminjaman/detail/$id': typeof AdminPeminjamanDetailIdLazyRoute
  '/admin/peminjaman/edit/$id': typeof AdminPeminjamanEditIdLazyRoute
  '/admin/ruangan/edit/$id': typeof AdminRuanganEditIdLazyRoute
  '/admin/student/edit/$id': typeof AdminStudentEditIdLazyRoute
  '/admin/tag/edit/$id': typeof AdminTagEditIdLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dokumen'
    | '/forgetpass'
    | '/informasi'
    | '/pengajuan'
    | '/prestasi'
    | '/register'
    | '/riwayat'
    | '/tentangKami'
    | '/testing'
    | '/login'
    | '/ruangan/$id'
    | '/admin'
    | '/ruangan'
    | '/admin/peminjaman/create'
    | '/admin/achievement/$id'
    | '/admin/achievement/create'
    | '/admin/berkas/create'
    | '/admin/fasilitas/create'
    | '/admin/ruangan/create'
    | '/admin/student/create'
    | '/admin/tag/create'
    | '/admin/peminjaman'
    | '/admin/achievement'
    | '/admin/berkas'
    | '/admin/fasilitas'
    | '/admin/ruangan'
    | '/admin/student'
    | '/admin/tag'
    | '/admin/achievement/edit/$id'
    | '/admin/berkas/edit/$id'
    | '/admin/fasilitas/edit/$id'
    | '/admin/peminjaman/detail/$id'
    | '/admin/peminjaman/edit/$id'
    | '/admin/ruangan/edit/$id'
    | '/admin/student/edit/$id'
    | '/admin/tag/edit/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dokumen'
    | '/forgetpass'
    | '/informasi'
    | '/pengajuan'
    | '/prestasi'
    | '/register'
    | '/riwayat'
    | '/tentangKami'
    | '/testing'
    | '/login'
    | '/ruangan/$id'
    | '/admin'
    | '/ruangan'
    | '/admin/peminjaman/create'
    | '/admin/achievement/$id'
    | '/admin/achievement/create'
    | '/admin/berkas/create'
    | '/admin/fasilitas/create'
    | '/admin/ruangan/create'
    | '/admin/student/create'
    | '/admin/tag/create'
    | '/admin/peminjaman'
    | '/admin/achievement'
    | '/admin/berkas'
    | '/admin/fasilitas'
    | '/admin/ruangan'
    | '/admin/student'
    | '/admin/tag'
    | '/admin/achievement/edit/$id'
    | '/admin/berkas/edit/$id'
    | '/admin/fasilitas/edit/$id'
    | '/admin/peminjaman/detail/$id'
    | '/admin/peminjaman/edit/$id'
    | '/admin/ruangan/edit/$id'
    | '/admin/student/edit/$id'
    | '/admin/tag/edit/$id'
  id:
    | '__root__'
    | '/'
    | '/dokumen'
    | '/forgetpass'
    | '/informasi'
    | '/pengajuan'
    | '/prestasi'
    | '/register'
    | '/riwayat'
    | '/tentangKami'
    | '/testing'
    | '/login'
    | '/ruangan/$id'
    | '/admin/'
    | '/ruangan/'
    | '/admin/peminjaman/create'
    | '/admin/achievement/$id'
    | '/admin/achievement/create'
    | '/admin/berkas/create'
    | '/admin/fasilitas/create'
    | '/admin/ruangan/create'
    | '/admin/student/create'
    | '/admin/tag/create'
    | '/admin/peminjaman/'
    | '/admin/achievement/'
    | '/admin/berkas/'
    | '/admin/fasilitas/'
    | '/admin/ruangan/'
    | '/admin/student/'
    | '/admin/tag/'
    | '/admin/achievement/edit/$id'
    | '/admin/berkas/edit/$id'
    | '/admin/fasilitas/edit/$id'
    | '/admin/peminjaman/detail/$id'
    | '/admin/peminjaman/edit/$id'
    | '/admin/ruangan/edit/$id'
    | '/admin/student/edit/$id'
    | '/admin/tag/edit/$id'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  DokumenRoute: typeof DokumenRoute
  ForgetpassRoute: typeof ForgetpassRoute
  InformasiRoute: typeof InformasiRoute
  PengajuanRoute: typeof PengajuanRoute
  PrestasiRoute: typeof PrestasiRoute
  RegisterRoute: typeof RegisterRoute
  RiwayatRoute: typeof RiwayatRoute
  TentangKamiRoute: typeof TentangKamiRoute
  TestingRoute: typeof TestingRoute
  LoginLazyRoute: typeof LoginLazyRoute
  RuanganIdLazyRoute: typeof RuanganIdLazyRoute
  AdminIndexRoute: typeof AdminIndexRoute
  RuanganIndexRoute: typeof RuanganIndexRoute
  AdminPeminjamanCreateRoute: typeof AdminPeminjamanCreateRoute
  AdminAchievementIdLazyRoute: typeof AdminAchievementIdLazyRoute
  AdminAchievementCreateLazyRoute: typeof AdminAchievementCreateLazyRoute
  AdminBerkasCreateLazyRoute: typeof AdminBerkasCreateLazyRoute
  AdminFasilitasCreateLazyRoute: typeof AdminFasilitasCreateLazyRoute
  AdminRuanganCreateLazyRoute: typeof AdminRuanganCreateLazyRoute
  AdminStudentCreateLazyRoute: typeof AdminStudentCreateLazyRoute
  AdminTagCreateLazyRoute: typeof AdminTagCreateLazyRoute
  AdminPeminjamanIndexRoute: typeof AdminPeminjamanIndexRoute
  AdminAchievementIndexLazyRoute: typeof AdminAchievementIndexLazyRoute
  AdminBerkasIndexLazyRoute: typeof AdminBerkasIndexLazyRoute
  AdminFasilitasIndexLazyRoute: typeof AdminFasilitasIndexLazyRoute
  AdminRuanganIndexLazyRoute: typeof AdminRuanganIndexLazyRoute
  AdminStudentIndexLazyRoute: typeof AdminStudentIndexLazyRoute
  AdminTagIndexLazyRoute: typeof AdminTagIndexLazyRoute
  AdminAchievementEditIdLazyRoute: typeof AdminAchievementEditIdLazyRoute
  AdminBerkasEditIdLazyRoute: typeof AdminBerkasEditIdLazyRoute
  AdminFasilitasEditIdLazyRoute: typeof AdminFasilitasEditIdLazyRoute
  AdminPeminjamanDetailIdLazyRoute: typeof AdminPeminjamanDetailIdLazyRoute
  AdminPeminjamanEditIdLazyRoute: typeof AdminPeminjamanEditIdLazyRoute
  AdminRuanganEditIdLazyRoute: typeof AdminRuanganEditIdLazyRoute
  AdminStudentEditIdLazyRoute: typeof AdminStudentEditIdLazyRoute
  AdminTagEditIdLazyRoute: typeof AdminTagEditIdLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  DokumenRoute: DokumenRoute,
  ForgetpassRoute: ForgetpassRoute,
  InformasiRoute: InformasiRoute,
  PengajuanRoute: PengajuanRoute,
  PrestasiRoute: PrestasiRoute,
  RegisterRoute: RegisterRoute,
  RiwayatRoute: RiwayatRoute,
  TentangKamiRoute: TentangKamiRoute,
  TestingRoute: TestingRoute,
  LoginLazyRoute: LoginLazyRoute,
  RuanganIdLazyRoute: RuanganIdLazyRoute,
  AdminIndexRoute: AdminIndexRoute,
  RuanganIndexRoute: RuanganIndexRoute,
  AdminPeminjamanCreateRoute: AdminPeminjamanCreateRoute,
  AdminAchievementIdLazyRoute: AdminAchievementIdLazyRoute,
  AdminAchievementCreateLazyRoute: AdminAchievementCreateLazyRoute,
  AdminBerkasCreateLazyRoute: AdminBerkasCreateLazyRoute,
  AdminFasilitasCreateLazyRoute: AdminFasilitasCreateLazyRoute,
  AdminRuanganCreateLazyRoute: AdminRuanganCreateLazyRoute,
  AdminStudentCreateLazyRoute: AdminStudentCreateLazyRoute,
  AdminTagCreateLazyRoute: AdminTagCreateLazyRoute,
  AdminPeminjamanIndexRoute: AdminPeminjamanIndexRoute,
  AdminAchievementIndexLazyRoute: AdminAchievementIndexLazyRoute,
  AdminBerkasIndexLazyRoute: AdminBerkasIndexLazyRoute,
  AdminFasilitasIndexLazyRoute: AdminFasilitasIndexLazyRoute,
  AdminRuanganIndexLazyRoute: AdminRuanganIndexLazyRoute,
  AdminStudentIndexLazyRoute: AdminStudentIndexLazyRoute,
  AdminTagIndexLazyRoute: AdminTagIndexLazyRoute,
  AdminAchievementEditIdLazyRoute: AdminAchievementEditIdLazyRoute,
  AdminBerkasEditIdLazyRoute: AdminBerkasEditIdLazyRoute,
  AdminFasilitasEditIdLazyRoute: AdminFasilitasEditIdLazyRoute,
  AdminPeminjamanDetailIdLazyRoute: AdminPeminjamanDetailIdLazyRoute,
  AdminPeminjamanEditIdLazyRoute: AdminPeminjamanEditIdLazyRoute,
  AdminRuanganEditIdLazyRoute: AdminRuanganEditIdLazyRoute,
  AdminStudentEditIdLazyRoute: AdminStudentEditIdLazyRoute,
  AdminTagEditIdLazyRoute: AdminTagEditIdLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.jsx",
      "children": [
        "/",
        "/dokumen",
        "/forgetpass",
        "/informasi",
        "/pengajuan",
        "/prestasi",
        "/register",
        "/riwayat",
        "/tentangKami",
        "/testing",
        "/login",
        "/ruangan/$id",
        "/admin/",
        "/ruangan/",
        "/admin/peminjaman/create",
        "/admin/achievement/$id",
        "/admin/achievement/create",
        "/admin/berkas/create",
        "/admin/fasilitas/create",
        "/admin/ruangan/create",
        "/admin/student/create",
        "/admin/tag/create",
        "/admin/peminjaman/",
        "/admin/achievement/",
        "/admin/berkas/",
        "/admin/fasilitas/",
        "/admin/ruangan/",
        "/admin/student/",
        "/admin/tag/",
        "/admin/achievement/edit/$id",
        "/admin/berkas/edit/$id",
        "/admin/fasilitas/edit/$id",
        "/admin/peminjaman/detail/$id",
        "/admin/peminjaman/edit/$id",
        "/admin/ruangan/edit/$id",
        "/admin/student/edit/$id",
        "/admin/tag/edit/$id"
      ]
    },
    "/": {
      "filePath": "index.lazy.jsx"
    },
    "/dokumen": {
      "filePath": "dokumen.jsx"
    },
    "/forgetpass": {
      "filePath": "forgetpass.jsx"
    },
    "/informasi": {
      "filePath": "informasi.jsx"
    },
    "/pengajuan": {
      "filePath": "pengajuan.jsx"
    },
    "/prestasi": {
      "filePath": "prestasi.jsx"
    },
    "/register": {
      "filePath": "register.jsx"
    },
    "/riwayat": {
      "filePath": "riwayat.jsx"
    },
    "/tentangKami": {
      "filePath": "tentangKami.jsx"
    },
    "/testing": {
      "filePath": "testing.jsx"
    },
    "/login": {
      "filePath": "login.lazy.jsx"
    },
    "/ruangan/$id": {
      "filePath": "ruangan/$id.lazy.jsx"
    },
    "/admin/": {
      "filePath": "admin/index.jsx"
    },
    "/ruangan/": {
      "filePath": "ruangan/index.jsx"
    },
    "/admin/peminjaman/create": {
      "filePath": "admin/peminjaman/create.jsx"
    },
    "/admin/achievement/$id": {
      "filePath": "admin/achievement/$id.lazy.jsx"
    },
    "/admin/achievement/create": {
      "filePath": "admin/achievement/create.lazy.jsx"
    },
    "/admin/berkas/create": {
      "filePath": "admin/berkas/create.lazy.jsx"
    },
    "/admin/fasilitas/create": {
      "filePath": "admin/fasilitas/create.lazy.jsx"
    },
    "/admin/ruangan/create": {
      "filePath": "admin/ruangan/create.lazy.jsx"
    },
    "/admin/student/create": {
      "filePath": "admin/student/create.lazy.jsx"
    },
    "/admin/tag/create": {
      "filePath": "admin/tag/create.lazy.jsx"
    },
    "/admin/peminjaman/": {
      "filePath": "admin/peminjaman/index.jsx"
    },
    "/admin/achievement/": {
      "filePath": "admin/achievement/index.lazy.jsx"
    },
    "/admin/berkas/": {
      "filePath": "admin/berkas/index.lazy.jsx"
    },
    "/admin/fasilitas/": {
      "filePath": "admin/fasilitas/index.lazy.jsx"
    },
    "/admin/ruangan/": {
      "filePath": "admin/ruangan/index.lazy.jsx"
    },
    "/admin/student/": {
      "filePath": "admin/student/index.lazy.jsx"
    },
    "/admin/tag/": {
      "filePath": "admin/tag/index.lazy.jsx"
    },
    "/admin/achievement/edit/$id": {
      "filePath": "admin/achievement/edit/$id.lazy.jsx"
    },
    "/admin/berkas/edit/$id": {
      "filePath": "admin/berkas/edit/$id.lazy.jsx"
    },
    "/admin/fasilitas/edit/$id": {
      "filePath": "admin/fasilitas/edit/$id.lazy.jsx"
    },
    "/admin/peminjaman/detail/$id": {
      "filePath": "admin/peminjaman/detail/$id.lazy.jsx"
    },
    "/admin/peminjaman/edit/$id": {
      "filePath": "admin/peminjaman/edit/$id.lazy.jsx"
    },
    "/admin/ruangan/edit/$id": {
      "filePath": "admin/ruangan/edit/$id.lazy.jsx"
    },
    "/admin/student/edit/$id": {
      "filePath": "admin/student/edit/$id.lazy.jsx"
    },
    "/admin/tag/edit/$id": {
      "filePath": "admin/tag/edit/$id.lazy.jsx"
    }
  }
}
ROUTE_MANIFEST_END */
